# Generated by Django 4.2 on 2023-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(max_length=9)),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('Street', models.CharField(max_length=45)),
                ('email_address', models.EmailField(max_length=40)),
            ],
        ),
    ]
