# Generated by Django 4.2 on 2023-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('Permission_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Permission_Name', models.CharField(max_length=45)),
            ],
        ),
    ]
