# Generated by Django 4.2 on 2023-04-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='Role_Role_ID',
            field=models.ManyToManyField(null=True, to='users.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='Role_Role_ID',
            field=models.ManyToManyField(null=True, to='users.user'),
        ),
    ]
