# Generated by Django 4.2 on 2023-04-26 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_role_role_id_permission_permission_has_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permeion_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permission')),
                ('role_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
        ),
    ]
