# Generated by Django 4.2 on 2023-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userroles_rolepermetion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='permission_has_role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_has_user',
        ),
        migrations.AddField(
            model_name='permission',
            name='per_to_role',
            field=models.ManyToManyField(through='users.RolePermetion', to='users.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_to_per',
            field=models.ManyToManyField(through='users.RolePermetion', to='users.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_to_user',
            field=models.ManyToManyField(through='users.UserRoles', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_to_role',
            field=models.ManyToManyField(through='users.UserRoles', to='users.role'),
        ),
    ]
