# Generated by Django 4.2 on 2023-04-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
        ('users', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_to_jop',
            field=models.ManyToManyField(through='freelance.UserApplyJobs', to='freelance.job'),
        ),
    ]
