# Generated by Django 4.2 on 2023-05-24 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_supportticket_user_re'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_remove_user_user_to_course_remove_user_user_to_jop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_fore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
