# Generated by Django 4.2 on 2023-05-29 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('jop_title', models.CharField(max_length=255)),
                ('descriotion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('jop_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_freelancer_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.job')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_descriotion', models.CharField(max_length=1000)),
                ('image_urls', models.CharField(max_length=1000)),
                ('audio_urls', models.CharField(max_length=1000)),
                ('videos_urls', models.CharField(max_length=1000)),
                ('attachements_urls', models.CharField(max_length=1000)),
                ('project_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jop_to_user',
            field=models.ManyToManyField(through='freelance.UserApplyJobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FreelancerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name_f', models.CharField(max_length=255)),
                ('transaction_date_f', models.DateTimeField(default=datetime.datetime.now)),
                ('freelancer_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.FloatField(max_length=5)),
                ('freelancer_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('major_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.major')),
            ],
        ),
    ]
