# Generated by Django 4.2 on 2023-04-27 03:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('jop_title', models.CharField(max_length=255)),
                ('descriotion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jop_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('user_freelancer_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jop_to_user',
            field=models.ManyToManyField(through='freelance.UserApplyJobs', to='users.user'),
        ),
        migrations.CreateModel(
            name='FreelancerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name_f', models.CharField(max_length=255)),
                ('transaction_date_f', models.DateTimeField(default=datetime.datetime.now)),
                ('freelancer_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
