# Generated by Django 4.2 on 2023-06-19 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_to_jop',
            field=models.ManyToManyField(related_name='jop_to_user', through='freelance.UserApplyJobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='major',
            name='user_to_Major',
            field=models.ManyToManyField(related_name='major_to_user', through='freelance.FreelancerData', to=settings.AUTH_USER_MODEL),
        ),
    ]
