# Generated by Django 4.2 on 2023-06-11 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_remove_freelancerdata_major_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancerdata',
            name='major_name',
        ),
        migrations.AddField(
            model_name='freelancerdata',
            name='image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_price',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_price',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancerdata',
            name='major_rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.major'),
        ),
        migrations.AddField(
            model_name='job',
            name='major_rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.major'),
        ),
    ]
