# Generated by Django 4.2 on 2023-06-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_major_remove_freelancerdata_major_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
