# Generated by Django 4.2 on 2023-06-11 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_alter_job_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
