# Generated by Django 4.2 on 2023-05-28 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance', '0004_alter_freelancertransaction_freelancer_rel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userapplyjobs',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FreelancerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.FloatField(max_length=5)),
                ('freelancer_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('major_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelance.major')),
            ],
        ),
    ]
