# Generated by Django 4.2 on 2023-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        ('freelance', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_to_course',
            field=models.ManyToManyField(through='courses.CourseRegister', to='courses.course'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_to_jop',
            field=models.ManyToManyField(through='freelance.UserApplyJobs', to='freelance.job'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_to_role',
            field=models.ManyToManyField(through='users.UserRoles', to='users.role'),
        ),
    ]
