# Generated by Django 4.2 on 2023-04-22 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('Ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
