# Generated by Django 4.2 on 2023-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_role_role_id_permission_permission_has_role_and_more'),
        ('support', '0002_supportticket_user_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='user_re',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_re',
            field=models.ManyToManyField(null=True, to='users.user'),
        ),
    ]
