# Generated by Django 4.2 on 2023-05-24 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_remove_supportticket_user_re_supportticket_user_re'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='user_re',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
