# Generated by Django 4.2 on 2023-06-19 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_to_course',
            field=models.ManyToManyField(related_name='course_to_user', through='courses.CourseRegister', to=settings.AUTH_USER_MODEL),
        ),
    ]
