# Generated by Django 4.2.1 on 2023-06-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseregister_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseregister',
            table='course_register',
        ),
    ]
