# Generated by Django 4.2.1 on 2023-06-11 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_courseregister_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_to_course',
            field=models.ManyToManyField(related_name='user', through='courses.CourseRegister', to=settings.AUTH_USER_MODEL),
        ),
    ]
