# Generated by Django 4.2.1 on 2023-06-11 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_course_user_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_to_course',
            field=models.ManyToManyField(through='courses.CourseRegister', to=settings.AUTH_USER_MODEL),
        ),
    ]
