# Generated by Django 4.2 on 2023-04-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_permission_permission_has_role_and_more'),
        ('courses', '0004_course_user_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_re',
        ),
        migrations.AddField(
            model_name='course',
            name='user_to_course',
            field=models.ManyToManyField(through='courses.CourseRegister', to='users.user'),
        ),
    ]
