# Generated by Django 4.2 on 2023-05-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_course_user_to_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseregister",
            name="rating",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
